DROP DATABASE IF EXISTS search;
CREATE DATABASE search;

CREATE USER 'search'@'%' IDENTIFIED BY 'search';
GRANT ALL PRIVILEGES ON search.* TO 'search'@'%';
FLUSH PRIVILEGES;

USE search;

DROP TABLE IF EXISTS search;
CREATE TABLE search(
	email	VARCHAR(100),
	bio		VARCHAR(250),
	PRIMARY KEY(email)
);